# config/packages/framework.yaml
framework:
    secret: '%env(APP_SECRET)%'
    # Disable HTTP method override for security
    http_method_override: false
    # Handle all throwables for better error handling
    handle_all_throwables: true
    # Session configuration
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    # Asset management configuration (important for your case)
    assets:
        packages:
            # Default package configuration
            _default:
                version: null
                version_format: '%%s?version=%%s'
                base_path: '/'
        # json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'  # Commented out
    # Error handling
    php_errors:
        log: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
